store/expenses/urls.py
from django.urls import path

from .views import ExpenseCustomCreateView
from .views import ExpenseCustomDeleteView
from .views import ExpenseCustomUpdateView
from .views import ExpenseListDatatableTemplateView
from .views import ExpenseListDownloadView
from .views import ExpenseTemplateView


app_name = 'expenses'


urlpatterns = [
    path(
        '',
        ExpenseTemplateView.as_view(),
        name='home'
    ),
    path(
        'list/',
        ExpenseListDatatableTemplateView.as_view(),
        name='list_expense'
    ),
    path(
        'create/',
        ExpenseCustomCreateView.as_view(),
        name='create_expense'
    ),
    path(
        'update/<int:id>',
        ExpenseCustomUpdateView.as_view(),
        name='update_expense'
    ),
    path(
        'delete/<int:id>',
        ExpenseCustomDeleteView.as_view(),
        name='delete_expense'
    ),
    path(
        'download/',
        ExpenseListDownloadView.as_view(),
        name='download_expense'
    ),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('', include('pos.urls')),
    path('accounts/', include('accounts.urls')),
    path('attendance/', include('attendance.urls')),
    path('admin/', admin.site.urls),
    path('calendar/', include('calendars.urls')),
    path('dashboard/', include('dashboards.urls')),
    path('expenses/', include('expenses.urls')),
    path('inventory/', include('inventory.urls')),
    path('payslip/', include('payslips.urls')),
]

urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store_system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

store/expenses/models.py
from django.db import models

from mixins.models import ModelMixin


class Expense(ModelMixin):
    """
    The cost you incur when paying bills, taxes, services for running
    the business.
    """

    ADS = 'ads'
    COMS = 'coms'
    ELECTRICITY = 'electricity'
    ENTERTAIN = 'entertain'
    FOOD = 'food'
    INSURANCE = 'insurance'
    INTERNET = 'internet'
    LOAN = 'loan'
    MAINTENANCE = 'maintenance'
    MISC = 'misc'
    PROF_FEE = 'prof_fee'
    RENT = 'rent'
    SALARY = 'salary'
    SOFTWARE = 'software'
    TAX = 'tax'
    TOOL = 'tool'
    TRANSPO = 'transpo'
    WATER = 'water'
    OTHER = 'other'

    CATEGORY_CHOICES = [
        (ADS, 'Advertisement'),
        (COMS, 'Communication'),
        (ELECTRICITY, 'Electricity'),
        (ENTERTAIN, 'Entertainment'),
        (FOOD, 'Food'),
        (INSURANCE, 'Insurance'),
        (INTERNET, 'Internet'),
        (LOAN, 'Loan'),
        (MAINTENANCE, 'Maintenance'),
        (MISC, 'Miscellaneous'),
        (PROF_FEE, 'Professional Fee'),
        (RENT, 'Rent'),
        (SALARY, 'Salary'),
        (SOFTWARE, 'Software'),
        (TAX, 'Taxes & Legal Fees'),
        (TOOL, 'Tools & Equipments'),
        (TRANSPO, 'Transportation & Fuel'),
        (WATER, 'Water'),
        (OTHER, 'Other'),
    ]
    
    expense_date = models.DateField()
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    address = models.TextField(blank=True, default='')
    tin_number = models.CharField(blank=True, max_length=255, default='')
    or_number = models.CharField(blank=True, max_length=255, default='')
    is_business = models.BooleanField(default=True)

    @classmethod
    def get_expenses_by_date_range(cls, start_date, end_date):
        """
        Retrieve and return a list of expenses within the specified date range.

        Params:
            start_date - datetime object
            end_date - datetime object
        """

        expenses = (
            cls.objects
                .filter(expense_date__range=(start_date, end_date))
                .values('expense_date', 'amount')
        )
        return expenses

store/expenses/forms.py
from django import forms

from .models import Expense


class ExpenseForm(forms.ModelForm):
    """
    Form used when creating an expense.
    """
    class Meta:
        model = Expense
        fields = [
            'expense_date',
            'name',
            'address',
            'tin_number',
            'or_number',
            'category',
            'amount',
            'is_business',
        ]

store/expenses/views.py
import io
import pandas as pd

from datetime import date
from datetime import datetime
from datetime import timedelta
from typing import Any

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import FileResponse
from django.http import Http404
from django.views import View
from django.views.generic import TemplateView

from braces.views import JSONResponseMixin

from .forms import ExpenseForm
from .models import Expense


class ExpenseTemplateView(LoginRequiredMixin, TemplateView):
    """
    Dashboard for expenses.
    """
    template_name = 'expenses/home.html'

    def get_filters(self, request):
        filters = self.request.session.get('filters', {})
        name_filter = request.POST.get('name_filter')
        category_filter = request.POST.get('category_filter')
        if name_filter:
            filters['name'] = name_filter
        if category_filter:
            filters['category'] = category_filter
        if request.POST.get('start_date') and request.POST.get('end_date'):
            start_date = datetime.strptime(request.POST.get('start_date'), settings.DATE_FORMAT)
            end_date = datetime.strptime(request.POST.get('end_date'), settings.DATE_FORMAT)
        elif filters.get('start_date') and filters.get('end_date'):
            start_date = datetime.strptime(filters.get('start_date'), '%Y-%m-%d')
            end_date = datetime.strptime(filters.get('end_date'), '%Y-%m-%d')
        else:
            start_date, end_date = self.get_initial_dates()
        if start_date:
            filters['start_date'] = start_date.strftime('%Y-%m-%d')
        if end_date:
            filters['end_date'] = end_date.strftime('%Y-%m-%d')
        self.request.session['filters'] = filters
        return filters

    def get_initial_dates(self):
        current_date = date.today()
        start_date = current_date - timedelta(days=7)
        end_date = current_date
        return start_date, end_date

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        if self.request.GET.get('clear') == 'True':
            self.request.session['filters'] = {}
        filters = self.get_filters(self.request)
        context['expense_form'] = ExpenseForm(initial={'amount': 0})
        context['expense_update_form'] = ExpenseForm(auto_id='id_%s_update')
        return context

    def post(self, request, **kwargs):
        context = super().get_context_data(**kwargs)
        filters = self.get_filters(request)
        context['expense_form'] = ExpenseForm(initial={'amount': 0})
        context['expense_update_form'] = ExpenseForm(auto_id='id_%s_update')
        context.update({
            'start_date': datetime.strptime(filters['start_date'], '%Y-%m-%d'),
            'end_date': datetime.strptime(filters['end_date'], '%Y-%m-%d'),
            'filters': filters,
        })
        return self.render_to_response(context)


class ExpenseCustomCreateView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    View used when creating expenses.
    """

    def post(self, request, *args, **kwargs):
        form = ExpenseForm(request.POST)
        if form.is_valid():
            expense = form.save(commit=False)
            expense.created_by = request.user
            expense.save()
            json_data = {
                'status': 'success',
                'message': 'Expense successfully created.'
            }
            return self.render_json_response(json_data, status=201)
        json_data = {'status': 'error', 'errors': form.errors}
        return self.render_json_response(json_data, status=400)


class ExpenseCustomDeleteView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    View used for deleting an expsense.
    """

    def post(self, request, *args, **kwargs):
        try:
            expense = Expense.objects.get(id=self.kwargs['id'])
        except Exception as e:
             # Object not found
             return self.render_json_response({'message': str(e)}, status=404)
        expense.delete()
        json_data = {
            'message': 'Successfully deleted'
        }
        return self.render_json_response(json_data, status=204)


class ExpenseCustomUpdateView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    View used for updating expenses.
    """

    def post(self, request, *args, **kwargs):
        form = ExpenseForm(request.POST)
        if form.is_valid():
            with transaction.atomic():
                try:
                    expense = Expense.objects.get(id=self.kwargs['id'])
                except Expense.DoesNotExist:
                    raise Http404('Expense does not exist')
                expense.name = form.cleaned_data['name']
                expense.category = form.cleaned_data['category']
                expense.amount = form.cleaned_data['amount']
                expense.expense_date = form.cleaned_data['expense_date']
                expense.updated_date = datetime.today()
                expense.updated_by = request.user
                expense.address = form.cleaned_data['address']
                expense.tin_number = form.cleaned_data['tin_number']
                expense.or_number = form.cleaned_data['or_number']
                expense.is_business = form.cleaned_data['is_business']
                expense.save()
                json_data = {
                    'status': 'success',
                    'message': 'Product variation successfully Updated.'
                }
                return  self.render_json_response(json_data, status=200)
        json_data = {'status': 'error', 'errors': form.errors}
        return self.render_json_response(json_data, status=400)


class ExpenseListDatatableTemplateView(LoginRequiredMixin, TemplateView):
    """
    Renders the datatable that contains the list of expenses.
    """
    template_name = 'expenses/datatables/expenses.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        start_date = datetime.strptime(self.request.session['filters']['start_date'], '%Y-%m-%d')
        end_date = datetime.strptime(self.request.session['filters']['end_date'], '%Y-%m-%d')
        filters = {
            'expense_date__range': (start_date, end_date),
        }
        if self.request.session['filters'].get('name'):
            name = self.request.session['filters'].get('name')
            filters.update({'name': name})
        if self.request.session['filters'].get('category'):
            category = self.request.session['filters'].get('category')
            filters.update({'category': category})
        context['expenses'] = (
            Expense.objects
                .filter(**filters)
                .order_by('-expense_date')
        )
        context['categories'] = Expense.CATEGORY_CHOICES
        context['names'] = Expense.objects.values_list('name', flat=True).distinct()
        context['start_date'] = start_date
        context['end_date'] = end_date
        context['filters'] = filters
        return context


class ExpenseListDownloadView(LoginRequiredMixin, View):
    """
    Download the datatable that contains the list of expenses into CSV.
    """
    
    def get(self, request, *args, **kwargs):
        DATE_FORMAT = "%m/%d/%Y"
        STATIC_FILTERS = {
            'tin_number':'',
            'or_number':'',
            }
        combined_filters = {}
        filters = self.request.session['filters']
        filter_list = {
            'expense_date__range': (filters['start_date'], filters['end_date'],), 
        }
        if filters.get('name'):
            name = filters.get('name')
            filter_list.update({'name': name})
        if filters.get('category'):
            category = filters.get('category')
            filter_list.update({'category': category})
        combined_filters = {**filter_list}        
        expenses_list = (
            Expense.objects
                .filter(**combined_filters)
                .exclude(**STATIC_FILTERS)
                .order_by('-expense_date')
                .values()
        )
        for expense in expenses_list:
            expense['created_date'] = (
                expense['created_date'].strftime(DATE_FORMAT) if expense['created_date'] else ""
            )
            expense['expense_date'] = (
                expense['expense_date'].strftime(DATE_FORMAT) if expense['expense_date'] else ""
            )
            expense['updated_date'] = (
                expense['updated_date'].strftime(DATE_FORMAT) if expense['updated_date'] else ""
            )
        expenses_summary = pd.DataFrame.from_records(expenses_list)
        buffer = io.BytesIO()
        expenses_summary.to_excel(buffer)
        buffer.seek(0)
        response = FileResponse(
            buffer,
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        start_date_name = datetime.strptime(filters['start_date'], "%Y-%m-%d").strftime("%b-%d, %Y")
        end_date_name = datetime.strptime(filters['end_date'], "%Y-%m-%d").strftime("%b-%d, %Y")
        filename = f'expense summary-{start_date_name} - {end_date_name}.xlsx'
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response

store/expenses/templates/expenses/forms/create_expense.html
{% load widget_tweaks %}
<div class="modal fade" id="expenseModal" tabindex="-1" role="dialog" aria-labelledby="expenseModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <form id="createExpenseForm" method="POST">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="expenseModalLabel">Add Expense</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% for field in expense_form %}
          <div class="form-row" style="margin-bottom: 1rem;">
            <label for="{{ field.auto_id }}">{{ field.label }}:</label>
            {% if field.field.widget.input_type != "checkbox" %}
              {{ field|add_class:"form-control" }}
            {% else %}
            <div class="col-lg-1">
              {{ field }}
            </div>
            {% endif %}
            <div id="{{ field.auto_id }}_error"></div>
          </div>
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="idCreateExpenseSave">Save</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  /**
   * Script for submitting the form.
   */
  $(document).ready(() => {
    let createExpenseForm = $('#createExpenseForm');
    let saveButton = $('#idCreateExpenseSave');
    let expenseModal = $('#expenseModal');

    /**
     * Remove all error messages on the form.
     */
    function clearErrorMessages() {
      $('[id^="id_"][id$="_error"]').empty();
    }

    function resetForm() {
      createExpenseForm[0].reset();
      clearErrorMessages();
    }

    // Event handler for modal close and reset the fields.
    expenseModal.on('hidden.bs.modal', () => {
      resetForm();
    });

    /**
     * Script for creating expense.
     */
    saveButton.on('click', () => {
      // Serialize the form data and convert it to JSON
      let formData = new FormData(createExpenseForm[0]);
      let spinner = `
      <div class="spinner-border text-light" role="status" style="height: 1.4rem; width: 1.4rem">
        <span class="sr-only">Loading...</span>
      </div>`;
      saveButton.html(spinner);
      axios.post("{% url 'expenses:create_expense' %}", formData)
        .then(function (response) {
          expenseModal.modal('hide');
          clearErrorMessages();
          reloadComponent("{% url 'expenses:list_expense' %}", 'idExpenseTableContainer', true);
        })
        .catch(function (error) {
          console.log(error.response.data);
          if (error.response && error.response.data) {
            let errors = error.response.data.errors;
            for (let field in errors) {
              let errorMsgs = errors[field];
              $(`#id_${field}_error`).html(`<div class="text-danger">${errorMsgs}</div>`);
            }
          }
        })
        .finally(function () {
          saveButton.html('Save');
        });
    });
  });
</script>
<script>
  /**
   * Apply Daterangepicker.
   */
  $(function() {
    $('#id_expense_date').daterangepicker({
      singleDatePicker: true,
      showDropdowns: true,
      minYear: 1980,
      maxYear: parseInt(moment().format('YYYY'), 10),
    });
  });
</script>

store/expenses/templates/expenses/forms/delete_expense.html
<div class="modal fade" id="expenseDeleteModal" tabindex="-1" role="dialog" aria-labelledby="expenseDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="expenseDeleteModalLabel">Confirm Deletion</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this item?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a href="#" id="deleteExpenseConfirmButton" data-url="#" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
<script>
  /**
   * Script for deleting an expense.
   */
  $(document).ready(function() {
    $('#idExpenseTableContainer').on('click', '.delete-expense', (event)=> {
      let deleteUrl = event.currentTarget.dataset.url;
      // Set the new action attribute for the form
      $('#deleteExpenseConfirmButton').attr('data-url', deleteUrl);
    });

    // When the button on the confirm modal is clicked this will fire a request using axios.
    $('#deleteExpenseConfirmButton').on('click', (event)=> {
      let deleteExpenseConfirmButton = $('#deleteExpenseConfirmButton');
      const header_data = {
        headers: {'X-CSRFToken': '{{ csrf_token }}'},
      };
      let deleteUrl = event.currentTarget.dataset.url;
      let spinner = `
      <div class="spinner-border text-light" role="status" style="height: 1.4rem; width: 1.4rem">
        <span class="sr-only">Loading...</span>
      </div>`;
      deleteExpenseConfirmButton.html(spinner);
      axios.post(deleteUrl, {}, header_data)
        .then(response => {
          reloadComponent("{% url 'expenses:list_expense' %}", 'idExpenseTableContainer', true);
          $('#expenseDeleteModal').modal('hide');
        })
        .catch(error => {
          console.error('Error:', error);
        })
        .finally(function () {
          deleteExpenseConfirmButton.html('Delete');
        });
    });
  });
</script>

store/expenses/templates/expenses/forms/update_expense.html
{% load widget_tweaks %}
<div class="modal fade" id="expenseUpdateModal" tabindex="-1" role="dialog" aria-labelledby="expenseUpdateModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <form id="expenseUpdateForm" method="POST">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="expenseUpdateModalLabel">Update Expense</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% for field in expense_update_form %}
          <div class="form-row" style="margin-bottom: 1rem;">
            <label for="{{ field.auto_id }}">{{ field.label }}:</label>
            {% if field.field.widget.input_type != "checkbox" %}
              {{ field|add_class:"form-control" }}
            {% else %}
            <div class="col-lg-1">
              {{ field }}
            </div>
            {% endif %}
            <div id="{{ field.auto_id }}_error"></div>
          </div>
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="idUpdateExpenseSave">Save</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  /**
   * Script for submitting the form.
   */
  $(document).ready(() => {
    let updateURL;
    $('#idExpenseTableContainer').on('click', '.update-expense', (event) => {
      let id = event.currentTarget.dataset.id;
      let name = event.currentTarget.dataset.name;
      let amount = event.currentTarget.dataset.amount;
      let category = event.currentTarget.dataset.category;
      let date = event.currentTarget.dataset.date;
      let address = event.currentTarget.dataset.address;
      let tinNumber = event.currentTarget.dataset.tin_number;
      let orNumber = event.currentTarget.dataset.or_number;
      let isBusiness = event.currentTarget.dataset.is_business === 'True';
      
      updateURL = event.currentTarget.dataset.url;

      // Set the values on the update form.
      $('#id_name_update').val(name);
      $('#id_amount_update').val(amount);
      $('#id_category_update').val(category);
      $('#id_expense_date_update').val(date);
      $('#id_address_update').val(address);
      $('#id_tin_number_update').val(tinNumber);
      $('#id_or_number_update').val(orNumber);
      $('#id_is_business_update').prop('checked', isBusiness);
      $('#expenseUpdateModal').modal('show');
    });

    let expenseUpdateForm = $('#expenseUpdateForm');
    let saveButton = $('#idUpdateExpenseSave');
    let expenseUpdateModal = $('#expenseUpdateModal');

    /**
     * Remove all error messages on the customer form.
     */
    function clearErrorMessages() {
      $('[id^="id_"][id$="_error"]').empty();
    }

    function resetForm() {
      expenseUpdateForm[0].reset();
      clearErrorMessages();
    }

    // Event handler for modal close and reset the fields.
    expenseUpdateModal.on('hidden.bs.modal', () => {
      resetForm();
    });

    /**
     * Script for creating/updating product information.
     */
    saveButton.on('click', () => {
      // Serialize the form data and convert it to JSON
      let formData = new FormData(expenseUpdateForm[0]);
      let spinner = `
      <div class="spinner-border text-light" role="status" style="height: 1.4rem; width: 1.4rem">
        <span class="sr-only">Loading...</span>
      </div>`;
      saveButton.html(spinner);
      axios.post(updateURL, formData)
        .then(function (response) {
          expenseUpdateModal.modal('hide');
          clearErrorMessages();
          reloadComponent("{% url 'expenses:list_expense' %}", 'idExpenseTableContainer', true);
        })
        .catch(function (error) {
          console.log(error.response.data);
          if (error.response && error.response.data) {
            let errors = error.response.data.errors;
            for (let field in errors) {
              let errorMsgs = errors[field];
              $(`#id_${field}_update_error`).html(`<div class="text-danger">${errorMsgs}</div>`);
            }
          }
        })
        .finally(function () {
          saveButton.html('Save');
        });
    });
  });
</script>
<script>
  /**
   * Apply Daterangepicker.
   */
  $(function() {
    $('#id_expense_date_update').daterangepicker({
      singleDatePicker: true,
      showDropdowns: true,
      minYear: 1980,
      maxYear: parseInt(moment().format('YYYY'), 10)
    });
  });
</script>