store/inventory/urls.py
from django.urls import path

from .views import DeliveryCustomCreateView
from .views import DeliveryListTemplateView
from .views import DeliveryReportTemplateView
from .views import ExportToExcel
from .views import ExportToShipView
from .views import InventoryTemplateView
from .views import OutOfStockPrintView
from .views import OutOfStockTemplateView
from .views import ProductCustomCreateView
from .views import ProductCustomUpdateView
from .views import ProductListDatatableTemplateView
from .views import ProductTemplateView
from .views import TopItemsDatatableTemplateView
from .views import ToShipTemplateView
from .views import UploadToShipView
from .views import VariationCustomCreateView
from .views import VariationCustomDeleteView
from .views import VariationCustomUpdateView
from .views import VariationListDatatableTemplateView


app_name = 'inventory'


urlpatterns = [
    path(
        '',
        InventoryTemplateView.as_view(),
        name='home'
    ),
    path(
        'products/list/',
        ProductListDatatableTemplateView.as_view(),
        name='list_product'
    ),
    path(
        'products/create/',
        ProductCustomCreateView.as_view(),
        name='create_product'
    ),
    path(
        'products/update/',
        ProductCustomUpdateView.as_view(),
        name='update_product'
    ),
    path(
        'products/<str:item_code>/',
        ProductTemplateView.as_view(),
        name='product'
    ),
    path(
        'products/<str:item_code>/variations/',
        VariationListDatatableTemplateView.as_view(),
        name='list_variation'
    ),
    path(
        'products/<str:item_code>/variations/create/',
        VariationCustomCreateView.as_view(),
        name='create_variation'
    ),
    path(
        'products/<str:item_code>/variations/update/<str:id>/',
        VariationCustomUpdateView.as_view(),
        name='update_variation'
    ),
    path(
        'products/<str:item_code>/variations/delete/<str:id>/',
        VariationCustomDeleteView.as_view(),
        name='delete_variation'
    ),
    path(
        'delivery/',
        DeliveryReportTemplateView.as_view(),
        name='delivery'
    ),
    path(
        'delivery/list/',
        DeliveryListTemplateView.as_view(),
        name='list_delivery'
    ),
    path(
        'delivery/<str:product_id>/',
        DeliveryCustomCreateView.as_view(),
        name='add_delivery'
    ),
    path(
        'out-of-stock/',
        OutOfStockTemplateView.as_view(),
        name='out_of_stock'
    ),
    path(
        'to-ship/',
        ToShipTemplateView.as_view(),
        name='to_ship'
    ),
    path(
        'upload/to-ship/',
        UploadToShipView.as_view(),
        name='to_ship_upload'
    ),
    path(
        'export/to-excel/',
        ExportToExcel.as_view(),
        name='export_to_excel'
    ),
    path(
        'export/to-ship/',
        ExportToShipView.as_view(),
        name='to_ship_export'
    ),
    path(
        'export/out-of-stock/',
        OutOfStockPrintView.as_view(),
        name='out_of_stock_export'
    ),
    path(
        'datatables/topitems/',
        TopItemsDatatableTemplateView.as_view(),
        name='topitems_product'
    ),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('', include('pos.urls')),
    path('accounts/', include('accounts.urls')),
    path('attendance/', include('attendance.urls')),
    path('admin/', admin.site.urls),
    path('calendar/', include('calendars.urls')),
    path('dashboard/', include('dashboards.urls')),
    path('expenses/', include('expenses.urls')),
    path('inventory/', include('inventory.urls')),
    path('payslip/', include('payslips.urls')),
]

urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store_system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

store/inventory/models.py
import uuid

from mixins.models import ModelMixin

from django.db import models
from django.db.models import Sum
from django.db.models import DecimalField
from django.db.models import ExpressionWrapper
from django.db.models import F


class Product(ModelMixin):
    """
    Represents an item in the inventory.
    """

    class Meta:
        db_table = 'products'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    item_code = models.CharField(max_length=20)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    capital = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    variation = models.CharField(max_length=255)
    sku = models.CharField(blank=True, max_length=255, default='')
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name
    
    @classmethod    
    def update_stock(cls, product_id, quantity_of_sale):
        """
        Class method to update the new stock of a product.
        """

        product = cls.objects.get(id=product_id)
        new_quantity = product.quantity - quantity_of_sale
        product.quantity = new_quantity
        product.save()
    
    @classmethod
    def stock_value(cls):
        """
        Returns the total value of stocks in terms of capital spent.
        """
        total_value = (
                cls.objects
                    .annotate(product_value=ExpressionWrapper(F('quantity') * F('capital'), output_field=DecimalField()))
                    .aggregate(total_value=Sum('product_value'))
            )
        return total_value['total_value']

class Delivery(ModelMixin):
    """
    Represents the movement of the stock of products.
    """
    
    class Meta:
        db_table = 'deliveries'

    DELIVER = 'deliver'
    RETURNED = 'returned'
    PULL_OUT = 'pull_out'
    VOID = 'void'
    DEFAULT_CHOICES = [
        (DELIVER, 'Deliver'),
    ]
    IN_CHOICES = [
        (DELIVER, 'Deliver'),
        (RETURNED, 'Returned Item'),
    ]
    OUT_CHOICES = [
        (PULL_OUT, 'Pull-out'),
        (VOID, 'Void'),
    ]
    DELIVER_CHOICES = IN_CHOICES + OUT_CHOICES

    product_id = models.CharField(max_length=255)
    product_item_code = models.CharField(max_length=255)
    product_name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField(default=1)
    running_stock = models.PositiveIntegerField(default=0)
    reason = models.CharField(max_length=50, choices=DELIVER_CHOICES, default=DELIVER)
    remarks = models.TextField(blank=True, default='')

store/inventory/views.py
import io
import os
import re
from datetime import date
from datetime import datetime
from datetime import timedelta
from pathlib import Path
from typing import Any
from typing import Dict

import numpy as np
import pandas as pd
from braces.views import JSONResponseMixin

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import CharField
from django.db.models.functions import Cast
from django.http import FileResponse
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView

from accounts.mapping import get_user_mapping
from dashboards.charts import get_top_sold_products
from pos.models import Sale
from .forms import DeliveryAddForm
from .forms import DeliverySubtractForm
from .forms import ProductForm
from .forms import ProductUpdateForm
from .forms import VariationUpdateForm
from .models import Delivery
from .models import Product
from .reports import combine_to_ship_orders
from .reports import get_product_stock
from .utils import parse_variation
from .validation import is_file_supported


class InventoryTemplateView(LoginRequiredMixin, TemplateView):
    """
    Dashboard for inventories.
    """
    template_name = 'inventory/home.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['product_form'] = ProductForm
        context['product_update_form'] = ProductUpdateForm(auto_id='id_%s_update')
        return context
    

class ProductListDatatableTemplateView(LoginRequiredMixin, TemplateView):
    """
    Render the datatable for the products.
    """

    template_name = 'inventory/datatables/products.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context =  super().get_context_data(**kwargs)
        context['products'] = Product.objects.values(
            'item_code',
            'name',
            'description'
        ).order_by('name').distinct()
        return context


class ProductCustomCreateView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    View used when creating products.
    """

    def post(self, request, *args, **kwargs):
        form = ProductForm(request.POST)
        if form.is_valid():
            with transaction.atomic():
                variations = parse_variation(request.POST)

                # Check if item code already exists.
                is_exist = Product.objects.filter(item_code=form.cleaned_data['item_code'])
                if is_exist:
                    form_error = {}
                    form_error['item_code'] = ['Item code already exists.']
                    json_data = {'status': 'error', 'errors': form_error}
                    return self.render_json_response(json_data, status=400)

                # Check if the variations are empty.
                invalid_variations = []
                for product_variation in variations:
                    if not product_variation['variation']:
                        invalid_variations.append(product_variation['orig_key'])
                if invalid_variations:
                    form_error = {}
                    for var_key in invalid_variations:
                        form_error[var_key] = ['This field is required.']
                    json_data = {'status': 'error', 'errors': form_error}
                    return self.render_json_response(json_data, status=400)
                
                # If items are valid then continue to save to the database.
                for product_variation in variations:
                    product = form.save(commit=False)
                    product.pk = None  # Reset the primary key to create a new instance.
                    product.sku = product_variation['sku']
                    product.variation = product_variation['variation']
                    product.price = product_variation['price']
                    product.capital = product_variation['capital']
                    product.created_by = request.user
                    product.save()
                json_data = {
                    'status': 'success',
                    'message': 'Product successfully created.'
                }
                return  self.render_json_response(json_data, status=201)
        json_data = {'status': 'error', 'errors': form.errors}
        return self.render_json_response(json_data, status=400)


class ProductCustomUpdateView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    View used when updating products.
    """

    def post(self, request, *args, **kwargs):
        form = ProductUpdateForm(request.POST)

        if form.is_valid():
            with transaction.atomic():
                try:
                    products = Product.objects.filter(item_code=request.POST['old_item_code'])
                except Product.DoesNotExist:
                    raise Http404('Product does not exist')

                # Check if item code already exists.
                is_exist = (
                    Product.objects
                        .filter(item_code=form.cleaned_data['item_code'])
                        .exclude(item_code=request.POST['old_item_code'])
                )
                if is_exist:
                    form_error = {}
                    form_error['item_code'] = ['Item code already exists.']
                    json_data = {'status': 'error', 'errors': form_error}
                    return self.render_json_response(json_data, status=400)

                for product in products:
                    product.item_code = form.cleaned_data['item_code']
                    product.name = form.cleaned_data['name']
                    product.description = form.cleaned_data['description']
                    product.updated_date = datetime.today()
                    product.updated_by = request.user
                    product.save()
                json_data = {
                    'status': 'success',
                    'message': 'Product successfully Updated.'
                }
                return  self.render_json_response(json_data, status=200)
        json_data = {'status': 'error', 'errors': form.errors}
        return self.render_json_response(json_data, status=400)


class ProductTemplateView(LoginRequiredMixin, TemplateView):
    """
    Renders the page of the specific product using item_code.
    """

    template_name = 'inventory/product.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        try:
            products = Product.objects.filter(item_code=self.kwargs['item_code'])
        except Product.DoesNotExist:
            raise Http404('Product does not exist')
        context['product'] = products[0]
        context['variations'] = products
        context['variation_update_form'] = VariationUpdateForm(auto_id='id_%s_update')
        context['delivery_add_form'] = DeliveryAddForm(auto_id='id_%s_add_deliver')
        context['delivery_subtract_form'] = DeliverySubtractForm(auto_id='id_%s_sub_deliver')
        return context
    

class VariationListDatatableTemplateView(LoginRequiredMixin, TemplateView):
    """
    Render the datatable for the product variations.
    """

    template_name = 'inventory/datatables/variations.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context =  super().get_context_data(**kwargs)
        context['variations'] = Product.objects.filter(item_code=self.kwargs['item_code']).order_by('quantity')
        return context


class VariationCustomCreateView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    View used when creating product variation.
    """

    def post(self, request, *args, **kwargs):
        with transaction.atomic():
            variations = parse_variation(request.POST)
            # Check if the variations are empty.
            invalid_variations = []
            for product_variation in variations:
                if not product_variation['variation']:
                    invalid_variations.append(product_variation['orig_key'])
            if invalid_variations:
                form_error = {}
                for var_key in invalid_variations:
                    form_error[var_key] = ['This field is required.']
                json_data = {'status': 'error', 'errors': form_error}
                return self.render_json_response(json_data, status=400)
            
            try:
                sample_product = Product.objects.filter(item_code=self.kwargs['item_code'])
            except Product.DoesNotExist:
                raise Http404('Product Does Not Exist')
            
            sample_product = sample_product[0]
            # If items are valid then continue to save to the database.
            for product_variation in variations:
                product = Product(
                    item_code=sample_product.item_code,
                    name=sample_product.name,
                    description=sample_product.description,
                )
                product.pk = None  # Reset the primary key to create a new instance.
                product.sku = product_variation['sku']
                product.variation = product_variation['variation']
                product.price = product_variation['price']
                product.capital = product_variation['capital']
                product.created_by = request.user
                product.save()
            json_data = {
                'status': 'success',
                'message': 'Product Variation successfully created.'
            }

store/inventory/templates/inventory/datatables/deliveries.html
<div class="table-responsive">
  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th class="text-center">Date</th>
        <th class="text-center">Type</th>
        <th class="text-center">Item</th>
        <th class="text-center">Quantity</th>
        <th class="text-center">Delivered/Pull-out by</th>
      </tr>
    </thead>
    <tbody>
      {% for delivery in deliveries %}
      <tr>
        <td class="text-center">{{ delivery.created_date|date:"m/d/Y" }}</td>
        <td class="text-center {% if delivery.reason in deliver_inchoices %}text-success{% else %}text-danger{% endif %}">{{ delivery.get_reason_display }}</td>
        <td class="text-center"><a href="{% url 'inventory:product' delivery.product_item_code %}">{{ delivery.product_name }}</a></td>
        <td class="text-center">{{ delivery.quantity }}</td>
        <td class="text-center">{{ delivery.created_by.username }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<script>
  /**
   * Apply datatable.net plugin on the table.
   */
  $(document).ready(function() {
    $('#dataTable').DataTable({
      order: [],
    });
  });
</script>

store/inventory/templates/inventory/datatables/products.html
<div class="table-responsive">
  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th class="text-center" style="width: 10%;">Item Code</th>
        <th class="text-center" style="width: 30%;">Product</th>
        {% if user.is_staff %}
        <th class="text-center" style="width: 50%;">Description</th>
        <th class="text-center" style="width: 10%;">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
      <tr>
        <td>{{ product.item_code }}</td>
        <td>
          <a href="{% url 'inventory:product' product.item_code %}">
            {{ product.name }}
          </a>
        </td>
        {% if user.is_staff %}
        <td>{{ product.description }}</td>
        <td class="text-center">
          <a 
            class="btn btn-warning update-product"
            data-item_code="{{ product.item_code }}"
            data-name="{{ product.name }}"
            data-description="{{ product.description }}"
          >
            <span class="icon text-white-50">
              <i class="fas fa-pen"></i>
            </span>
          </a>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<script>
  /**
   * Apply datatable.net plugin on the table.
   */
  $(document).ready(function() {
    $('#dataTable').DataTable({
      order: [],
      pageLength: parseInt("{{ DATATABLES_LENGTH }}"),
    });
  });
</script>

store/inventory/templates/inventory/datatables/topitems.html
<div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <thead> 
        <tr>
          <th class="text-center" style="width: 20%;">Ranking</th>
          <th class="text-center" style="width: 20%;">Name</th>
          <th class="text-center" style="width: 20%;">Quantity</th>
          <th class="text-center" style="width: 20%;">Est. Profit</th>
          <th class="text-center" style="width: 20%;">Ave. Profit/Item</th>
        </tr>      
      </thead>
      <tbody>
        {% for product in page_obj.object_list %}
        <tr>
          <td class="text-center">{{ forloop.counter0|add:page_obj.start_index }}</td>
          <td class="text-center">{{ product.name }}</td>
          <td class="text-center">{{ product.quantity }}</td>
          <td class="text-center">{{ product.computed_profit }}</td>
          <td class="text-center">{{ product.ave_profit_per_pc }}</td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
    <nav aria-label="" class="d-flex justify-content-center">
      <ul class="pagination">
        <li class="page-item">
          <button id="idPrevBtn" class="page-link" data-page="{{ page|add:-1}}" {% if page == 1 %}disabled{% endif %}>Prev</button>
        </li>
        {% for page_num in page_range %}
        <li class="page-item">
          <button class="page-link" data-page="{{ page_num }}">{{ page_num }}</button>
        </li>
        {% endfor %}
        <li class="page-item">
          <button id="idNextBtn" class="page-link" data-page="{{ page|add:1}}" {% if page == last_page %}disabled{% endif %}>Next</button>
        </li>
      </ul>
    </nav>
</div>

store/inventory/templates/inventory/datatables/variations.html
<div class="table-responsive">
  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th class="text-center">SKU</th>
        <th class="text-center">Variation</th>
        {% if user.is_staff %}
        <th class="text-center">Capital</th>
        {% endif %}
        <th class="text-center">Price</th>
        <th class="text-center">Quantity</th>
        <th class="text-center">Delivery</th>
        {% if user.is_staff %}
        <th class="text-center">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for variation in variations %}
      <tr>
        <td>{{ variation.sku }}</td>
        <td>{{ variation.variation }}</td>
        {% if user.is_staff %}
        <td>{{ variation.capital }}</td>
        {% endif %}
        <td>{{ variation.price }}</td>
        <td>{% if not variation.quantity %}<span class="badge badge-pill badge-danger">0ut of stock</span>{% else %}{{ variation.quantity }}{% endif %}</td>
        <td class="text-center">
          <a
            class="btn btn-success add-delivery"
            data-id="{{ variation.id }}"
            data-name="{{ variation.name }}"
            data-variation="{{ variation.variation }}"
            data-url="{% url 'inventory:add_delivery' variation.id %}"
          >
            <span class="icon text-white-50">
              <i class="fas fa-truck"></i>
            </span>
          </a>
          <a
            class="btn btn-danger subtract-delivery"
            data-id="{{ variation.id }}"
            data-name="{{ variation.name }}"
            data-variation="{{ variation.variation }}"
            data-url="{% url 'inventory:add_delivery' variation.id %}"
          >
            <span class="icon text-white-50">
              <i class="fas fa-cart-arrow-down"></i>
            </span>
          </a>
        </td>
        {% if user.is_staff %}
        <td class="text-center">
          <a
            class="btn btn-warning update-variation"
            data-id="{{ variation.id }}"
            data-sku="{{ variation.sku }}"
            data-variation="{{ variation.variation }}"
            data-price="{{ variation.price }}"
            data-quantity="{{ variation.quantity }}"
            data-capital="{{ variation.capital }}"
            data-url="{% url 'inventory:update_variation' variation.item_code variation.id %}"
          >
            <span class="icon text-white-50">
              <i class="fas fa-pen"></i>
            </span>
          </a>
          <a
            class="btn btn-danger delete-variation"
            data-toggle="modal"
            data-target="#variationDeleteModal"
            data-url="{% url 'inventory:delete_variation' variation.item_code variation.id %}"
          >
            <span class="icon text-white-50">
              <i class="fas fa-trash"></i>
            </span>
          </a>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<script>
  /**
   * Apply datatable.net plugin on the table.
   */
  $(document).ready(function() {
    $('#dataTable').DataTable({
      order: [
        [3, 'asc']
      ],
    });
  });
</script>