store/accounts/urls.py
from django.urls import path

from .views import LoginView
from .views import logout_view

from .views import AccountComponentTemplateView
from .views import AccountCustomCreateView
from .views import AccountCustomDeleteView
from .views import AccountCustomUpdateView
from .views import AccountListDatatableTemplateView

app_name = 'accounts'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        logout_view,
        name='logout'
    ),
    path(
        '',
        AccountComponentTemplateView.as_view(),
        name='home'
    ),
    path(
        'accounts/list/',
        AccountListDatatableTemplateView.as_view(),
        name='list_account'
    ),
    path(
        'create/',
        AccountCustomCreateView.as_view(),
        name='create_account'
    ),
    path(
        'delete/<int:id>/',
        AccountCustomDeleteView.as_view(),
        name='delete_account'
    ),
    path(
        'update/<int:id>/',
        AccountCustomUpdateView.as_view(),
        name='update_account'
    ),
]

store/calendars/urls.py
from django.urls import path

from .views import CalendarComponentTemplateView
from .views import CalendarTemplateView


app_name = 'calendars'


urlpatterns = [
    path(
        '',
        CalendarTemplateView.as_view(),
        name='home'
    ),
    path(
        'calendar/',
        CalendarComponentTemplateView.as_view(),
        name='component'
    ),
]

store/dashboards/urls.py
from django.urls import path

from .views import ChartTemplateView
from .views import DashboardSummaryTemplateView
from .views import DashboardTemplateView


app_name = 'dashboards'


urlpatterns = [
    path(
        '',
        DashboardTemplateView.as_view(),
        name='home'
    ),
    path(
        'summary/',
        DashboardSummaryTemplateView.as_view(),
        name='dashboard_summary'
    ),
    path(
        'chart/',
        ChartTemplateView.as_view(),
        name='chart'
    ),
]

store/expenses/urls.py
from django.urls import path

from .views import ExpenseCustomCreateView
from .views import ExpenseCustomDeleteView
from .views import ExpenseCustomUpdateView
from .views import ExpenseListDatatableTemplateView
from .views import ExpenseListDownloadView
from .views import ExpenseTemplateView


app_name = 'expenses'


urlpatterns = [
    path(
        '',
        ExpenseTemplateView.as_view(),
        name='home'
    ),
    path(
        'list/',
        ExpenseListDatatableTemplateView.as_view(),
        name='list_expense'
    ),
    path(
        'create/',
        ExpenseCustomCreateView.as_view(),
        name='create_expense'
    ),
    path(
        'update/<int:id>',
        ExpenseCustomUpdateView.as_view(),
        name='update_expense'
    ),
    path(
        'delete/<int:id>',
        ExpenseCustomDeleteView.as_view(),
        name='delete_expense'
    ),
    path(
        'download/',
        ExpenseListDownloadView.as_view(),
        name='download_expense'
    ),
]

store/inventory/urls.py
from django.urls import path

from .views import DeliveryCustomCreateView
from .views import DeliveryListTemplateView
from .views import DeliveryReportTemplateView
from .views import ExportToExcel
from .views import ExportToShipView
from .views import InventoryTemplateView
from .views import OutOfStockPrintView
from .views import OutOfStockTemplateView
from .views import ProductCustomCreateView
from .views import ProductCustomUpdateView
from .views import ProductListDatatableTemplateView
from .views import ProductTemplateView
from .views import TopItemsDatatableTemplateView
from .views import ToShipTemplateView
from .views import UploadToShipView
from .views import VariationCustomCreateView
from .views import VariationCustomDeleteView
from .views import VariationCustomUpdateView
from .views import VariationListDatatableTemplateView


app_name = 'inventory'


urlpatterns = [
    path(
        '',
        InventoryTemplateView.as_view(),
        name='home'
    ),
    path(
        'products/list/',
        ProductListDatatableTemplateView.as_view(),
        name='list_product'
    ),
    path(
        'products/create/',
        ProductCustomCreateView.as_view(),
        name='create_product'
    ),
    path(
        'products/update/',
        ProductCustomUpdateView.as_view(),
        name='update_product'
    ),
    path(
        'products/<str:item_code>/',
        ProductTemplateView.as_view(),
        name='product'
    ),
    path(
        'products/<str:item_code>/variations/',
        VariationListDatatableTemplateView.as_view(),
        name='list_variation'
    ),
    path(
        'products/<str:item_code>/variations/create/',
        VariationCustomCreateView.as_view(),
        name='create_variation'
    ),
    path(
        'products/<str:item_code>/variations/update/<str:id>/',
        VariationCustomUpdateView.as_view(),
        name='update_variation'
    ),
    path(
        'products/<str:item_code>/variations/delete/<str:id>/',
        VariationCustomDeleteView.as_view(),
        name='delete_variation'
    ),
    path(
        'delivery/',
        DeliveryReportTemplateView.as_view(),
        name='delivery'
    ),
    path(
        'delivery/list/',
        DeliveryListTemplateView.as_view(),
        name='list_delivery'
    ),
    path(
        'delivery/<str:product_id>/',
        DeliveryCustomCreateView.as_view(),
        name='add_delivery'
    ),
    path(
        'out-of-stock/',
        OutOfStockTemplateView.as_view(),
        name='out_of_stock'
    ),
    path(
        'to-ship/',
        ToShipTemplateView.as_view(),
        name='to_ship'
    ),
    path(
        'upload/to-ship/',
        UploadToShipView.as_view(),
        name='to_ship_upload'
    ),
    path(
        'export/to-excel/',
        ExportToExcel.as_view(),
        name='export_to_excel'
    ),
    path(
        'export/to-ship/',
        ExportToShipView.as_view(),
        name='to_ship_export'
    ),
    path(
        'export/out-of-stock/',
        OutOfStockPrintView.as_view(),
        name='out_of_stock_export'
    ),
    path(
        'datatables/topitems/',
        TopItemsDatatableTemplateView.as_view(),
        name='topitems_product'
    ),
]

store/pos/urls.py
from django.urls import path

from .views import POSCheckOutTemplateView
from .views import POSProductListTemplateView
from .views import POSTemplateView
from .views import SaleVoidJSONView
from .views import ProductSoldListTemplateView
from .views import ProductSoldTemplateView
from .views import RecentlySoldTemplateView
from .views import SaleCustomCreateView
from .views import SaleReportTemplateView


app_name = 'pos'


urlpatterns = [
    path(
        '',
        POSTemplateView.as_view(),
        name='home'
    ),
    path(
        'products/',
        POSProductListTemplateView.as_view(),
        name='list_product'
    ),
    path(
        'checkout/',
        POSCheckOutTemplateView.as_view(),
        name='checkout'
    ),
    path(
        'sales/create/',
        SaleCustomCreateView.as_view(),
        name='create_sale'
    ),
    path(
        'sales/',
        SaleReportTemplateView.as_view(),
        name='sale'
    ),
    path(
        'sales/<str:receipt_number>/',
        ProductSoldTemplateView.as_view(),
        name='sold'
    ),
    path(
        'sales/<str:receipt_number>/products/',
        ProductSoldListTemplateView.as_view(),
        name='list_sold'
    ),
    path(
        'sales/void/<str:id>/',
        SaleVoidJSONView.as_view(),
        name='void'
    ),
    path(
        'sales/recent',
        RecentlySoldTemplateView.as_view(),
        name='recent'
    ),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('', include('pos.urls')),
    path('accounts/', include('accounts.urls')),
    path('attendance/', include('attendance.urls')),
    path('admin/', admin.site.urls),
    path('calendar/', include('calendars.urls')),
    path('dashboard/', include('dashboards.urls')),
    path('expenses/', include('expenses.urls')),
    path('inventory/', include('inventory.urls')),
    path('payslip/', include('payslips.urls')),
]

urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store_system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

store/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

from .models import Employee


class LoginForm(AuthenticationForm):
    """
    Form used for logging in.
    """
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput()
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput()
    )


class EmployeeForm(forms.ModelForm):
    """
    Forms for Employee Model.
    """
    class Meta:
        model = Employee
        fields = ['base_pay', 'designation', 'department']


class UserForm(forms.ModelForm):
    """
    Forms for User Model.
    """
    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'email',
            'first_name',
            'last_name',
            'is_staff',
            'is_superuser'
        ]


    def clean_username(self):
        username = self.cleaned_data.get('username')
        if self.instance and self.instance.username == username:
            return username
        elif User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken.")
        return username

store/payslips/forms.py
from django import forms

from .models import Payslip

class PayslipForm(forms.ModelForm):
    """
    Form used when creating an expense.
    """
    class Meta:
        model = Payslip
        fields = [
            'employee',
            'start_date',
            'end_date',
        ]

store/accounts/views.py
import datetime
from pytz import timezone
from typing import Any
from typing import Dict

import pandas as pd
from braces.views import JSONResponseMixin

from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import transaction
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView
from django.views.generic import FormView

from .forms import LoginForm
from .forms import EmployeeForm
from .forms import UserForm
from .models import Employee


class LoginView(FormView):
    """
    View used for logging in.
    """

    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        if not self.request.user.is_staff:
            self.success_url = reverse_lazy('calendars:home')
        return super().form_valid(form)


def logout_view(request):
    """
    View used for logging out the user.
    """
    logout(request)
    return redirect(reverse_lazy('accounts:login'))


class AccountComponentTemplateView(LoginRequiredMixin, JSONResponseMixin, TemplateView):
    """
    Creating User Account, Employee, Admin for Galinduh Web App
    """
    template_name = 'home.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['employee_form'] = EmployeeForm(initial={'base_pay': 0})
        context['user_form'] = UserForm
        context['update_employee_form'] = EmployeeForm(auto_id='id_%s_update')
        context['update_user_form'] = UserForm(auto_id='id_%s_update')
        return context

    def post(self, request, **kwargs):
        context = super().get_context_data(**kwargs)
        context['employee_form'] = EmployeeForm(initial={'base_pay': 0})
        context['user_form'] = UserForm
        context['update_employee_form'] = EmployeeForm(auto_id='id_%s_update')
        context['update_user_form'] = UserForm(auto_id='id_%s_update')
        return self.render_to_response(context)


class AccountListDatatableTemplateView(LoginRequiredMixin, TemplateView):
    """
    List of all account user.
    """
    template_name = 'accounts/datatables/accounts.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        users = list(User.objects.values().order_by('is_superuser', 'first_name'))
        employees = list(Employee.objects.values('user_id', 'base_pay', 'designation', 'department'))
        for user in users:
            for employee in employees:
                if user['id'] == employee['user_id']:
                    user.update(employee)
        context['users'] = users
        return context


class AccountCustomCreateView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    Creating User Account, Employee, Admin for Galinduh Web App.
    """
    def post(self, request, *args, **kwargs):
        user_form = UserForm(request.POST)
        employee_form = EmployeeForm(request.POST)
        if user_form.is_valid() and employee_form.is_valid():
            with transaction.atomic():
                accounts = User.objects.values('username')
                user = user_form.cleaned_data
                employee = employee_form.cleaned_data
                if not accounts.filter(username=user['username']).exists():
                    user.update({'date_joined': datetime.datetime.now(timezone('Asia/Manila'))})
                    User.objects.create_user(**user)
                    employee.update({
                        'user_id': User.objects.filter(username=user['username'])
                        .values_list('id',flat=True)
                        .get()
                    })
                    Employee.objects.create(**employee)
                    json_data = {
                        'status': 'success',
                        'message': 'Account successfully created.'
                    }
                    return self.render_json_response(json_data, status=201)
        if employee_form.errors:
            user_form.errors.update(employee_form.errors)
        json_data = {
            'status': 'error',
            'errors': user_form.errors
        }
        return self.render_json_response(json_data, status=400)


class AccountCustomDeleteView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    Deleting User Account, Employee, Admin.
    """
    def post(self, request, *args, **kwargs):
        try:
            user = User.objects.get(id=self.kwargs['id'])
        except Exception as e:
             # Object not found
             return self.render_json_response({'message': str(e)}, status=404)
        user.delete()
        json_data = {
            'message': 'Account Successfully deleted'
        }
        return self.render_json_response(json_data, status=204)


class AccountCustomUpdateView(LoginRequiredMixin, JSONResponseMixin, View):
    """
    Updating User Account, Employee, Admin.
    """
    def post(self, request, *args, **kwargs):
        account = User.objects.get(id=self.kwargs['id'])
        update_user_form = UserForm(request.POST, instance=account)
        update_employee_form = EmployeeForm(request.POST)
        if update_user_form.is_valid() and update_employee_form.is_valid():
            with transaction.atomic():
                account_data = update_user_form.cleaned_data
                employee_data = update_employee_form.cleaned_data
                # Check if the password is not the same with the current and starts with pbkdf2 for hashed so it wouldn't set the hashed password
                if not account.check_password(account_data):
                    if not account_data['password'].startswith('pbkdf2_'):
                        account.set_password(account_data['password'])
                # User update
                account.username = account_data['username']
                account.email = account_data['email']
                account.first_name = account_data['first_name']
                account.last_name = account_data['last_name']
                account.is_staff = account_data['is_staff']
                account.is_superuser = account_data['is_superuser']
                account.save()
                # Employee update
                if Employee.objects.filter(user__id=self.kwargs['id']).exists():
                    employee = Employee.objects.get(user__id=self.kwargs['id'])
                    employee.base_pay = employee_data['base_pay']
                    employee.designation = employee_data['designation']
                    employee.department = employee_data['department']
                    employee.save()
                else:
                    employee_data.update({
                        'user_id': self.kwargs['id']
                    })
                    Employee.objects.create(**employee_data)
                json_data = {
                    'status': 'success',
                    'message': 'Updated successfully.'
                }
                return self.render_json_response(json_data, status=200)
        if update_employee_form.errors:
            update_user_form.errors.update(update_employee_form.errors)
        json_data = {
            'status': 'error',
            'errors': update_user_form.errors
        }
        return self.render_json_response(json_data, status=400)

store/templates/alerts.html
<style>
  .alert {
    display: none;
    position: absolute;
    bottom: 0;
    right: 0;
    transform: translate(-1%, -4rem);
  }
</style>

<!-- Success Alert -->
<div id="idAlertSuccess" class="alert alert-success alert-dismissible" role="alert">
  <strong>Success!</strong> <span id="idAlertMessageSuccess"></span>
  <button type="button" class="close" data-target="idAlertSuccess" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<!-- Error Alert -->
<div id="idAlertError" class="alert alert-danger alert-dismissible" role="alert">
  <strong>Error!</strong> <span id="idAlertMessageError"></span>
  <button type="button" class="close" data-target="idAlertError" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<script>
  $('.close').on('click', (event)=> {
    let idAlert = event.currentTarget.dataset.target;
    $(`#${idAlert}`).addClass('d-none');
  });
</script>

store/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{ PROJECT_NAME }}</title>
    <!-- SEO Meta Tags-->
    <meta name="description" content="{{ PROJECT_NAME }}">
    <meta name="keywords" content="clothing, shop, e-commerce, market, jacket, shoes,  watches">
    <meta name="author" content="{{ PROJECT_NAME }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    <link rel="icon" type="image/x-icon" href="{{ FAVICON_LINK }}">

    <!-- Css stylesheet -->
    <link rel="stylesheet" media="screen" href="{% static 'css/sb-admin-2.min.css' %}">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Scripts -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script defer src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script defer src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script defer src="{% static 'js/sb-admin-2.min.js' %}"></script>
    <script src="{% static 'js/generic/component-utils.js' %}"></script>

    <!-- Page level plugins -->
    <script defer src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <!-- DataTables.net css -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- DateRangePicker -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

    <!-- FullCalendarJs -->
    <script src='https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.15/index.global.min.js'></script>
    <script src='https://cdn.jsdelivr.net/npm/@fullcalendar/web-component@6.1.15/index.global.min.js'></script>
    <script src='https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@6.1.15/index.global.min.js'></script>

    <!-- Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    {% block css %}{% endblock %}
  </head>
  <body>
    <div id="wrapper">
      {% include 'sidebar.html' %}
      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          {% include 'navigation.html' %}
          <div class="container-fluid">
            <!-- Page Heading -->
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
              <h1 class="h3 mb-0 text-gray-800">{% block header %}{% endblock %}</h1>
              {% block button %}{% endblock %}
            </div>
            {% block content %}{% endblock %}
          </div>
        </div>
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; {{ PROJECT_NAME }} 2023</span>
            </div>
          </div>
        </footer>
      </div>
      <!-- End of Content Wrapper -->
      {% block javascript %}{% endblock %}
    </div>

    <!-- Alerts (Success messages/error messages) -->
    {% include 'alerts.html' %}

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Logout</a>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

store/templates/sidebar.html
{% load static %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a 
    class="sidebar-brand d-flex align-items-center justify-content-center"
    {% if user.is_staff %}
    href="{% url 'dashboards:home' %}"
    {% else %}
    href="{% url 'pos:home' %}"
    {% endif %}
  >
    <div class="sidebar-brand-icon">
      <img src="{{ LOGO_LINK }}" class="" style="height: 3rem"/>
    </div>
    <div class="sidebar-brand-text mx-3">{{ PROJECT_NAME }}</div>
  </a>

  <hr class="sidebar-divider my-0">
  {% if user.is_staff %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'dashboards:home' %}">
      <i class="fas fa fa-chart-area"></i>
      <span>Dashboard</span>
    </a>
  </li>
  {% endif %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'calendars:home' %}">
      <i class="fas fa fa-calendar"></i>
      <span>Calendar</span>
    </a>
  </li>

  <hr class="sidebar-divider">
  <div class="sidebar-heading my-1">Management</div>

  {% if user.is_staff %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'accounts:home' %}">
      <i class="fa fa-user" aria-hidden="true"></i>
      <span>User</span>
    </a>
  </li>
  {% endif %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'pos:home' %}">
      <i class="fas fa-fw fa-cash-register"></i>
      <span>POS</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{% url 'inventory:home' %}">
      <i class="fas fa-fw fa-list-alt"></i>
      <span>Inventory</span>
    </a>
  </li>

  {% if user.is_staff %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'expenses:home' %}">
      <i class="fas fa-fw fa-wallet"></i>
      <span>Expenses</span>
    </a>
  </li>
  {% endif %}

  <hr class="sidebar-divider">
  <div class="sidebar-heading my-1">Reports</div>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'pos:sale' %}">
      <i class="fas fa-fw fa-book"></i>
      <span>Sales</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'inventory:delivery' %}">
      <i class="fas fa-fw fa-truck"></i>
      <span>Deliveries</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'inventory:out_of_stock' %}">
      <i class="fas fa-fw fa-shopping-basket"></i>
      <span>Out of stock</span>
    </a>
  </li>
  {% if user.is_staff %}
  <li class="nav-item">
    <a
      class="nav-link collapsed"
      href="#"
      data-toggle="collapse"
      data-target="#collapsePages"
      aria-expanded="true"
      aria-controls="collapsePages"
    >
      <i class="fas fa-fw fa-folder"></i>
      <span>Generate</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Reports:</h6>
        <a class="collapse-item" href="{% url 'inventory:to_ship' %}">To Ship</a>
        <a class="collapse-item" href="{% url 'inventory:export_to_excel' %}" target="_blank">Export Stocks</a>
      </div>
    </div>
  </li>
  {% endif %}
  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">
</ul>
<!-- End of Sidebar -->

store/templates/success_message.html
<div class="alert alert-success alert-dismissible fade show" role="alert" style="margin: 0">
  Success
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>